<?php

declare(strict_types=1);

return [
    [
        'key' => 'sp500',
        'name' => 'S&P 500',
        'symbol' => 'SPX',
        'identifier' => 'Index',
        'provider' => 'yahoo_chart',
        'provider_symbol' => '^GSPC',
        'decimals' => 2,
        'value_style' => 'number',
        'change_basis' => 'previous close',
    ],
    [
        'key' => 'vanguard_all_world',
        'name' => 'Vanguard All-World Acc',
        'symbol' => 'VWCE',
        'identifier' => 'IE00BK5BQT80',
        'provider' => 'yahoo_chart',
        'provider_symbol' => 'VWCE.DE',
        'decimals' => 2,
        'value_style' => 'money',
        'change_basis' => 'previous close',
    ],
    [
        'key' => 'vuag',
        'name' => 'S&P 500 UCITS Acc',
        'symbol' => 'VUAG',
        'identifier' => 'VUAG.L',
        'provider' => 'yahoo_chart',
        'provider_symbol' => 'VUAG.L',
        'decimals' => 2,
        'value_style' => 'money',
        'change_basis' => 'previous close',
    ],
    [
        'key' => 'veua',
        'name' => 'Developed Europe Acc',
        'symbol' => 'VEUA',
        'identifier' => 'VEUA.L',
        'provider' => 'yahoo_chart',
        'provider_symbol' => 'VEUA.L',
        'decimals' => 2,
        'value_style' => 'money',
        'change_basis' => 'previous close',
    ],
    [
        'key' => 'vfeg',
        'name' => 'Emerging Markets Acc',
        'symbol' => 'VFEG',
        'identifier' => 'VFEG.L',
        'provider' => 'yahoo_chart',
        'provider_symbol' => 'VFEG.L',
        'decimals' => 2,
        'value_style' => 'money',
        'change_basis' => 'previous close',
    ],
    [
        'key' => 'vjpb',
        'name' => 'Japan Acc',
        'symbol' => 'VJPB',
        'identifier' => 'VJPB.L',
        'provider' => 'yahoo_chart',
        'provider_symbol' => 'VJPB.L',
        'decimals' => 2,
        'value_style' => 'money',
        'change_basis' => 'previous close',
    ],
    [
        'key' => 'euro_gov_bond_1_3',
        'name' => 'Euro Govt Bond 1–3Y',
        'symbol' => 'IBGS',
        'identifier' => 'IE00B14X4Q57',
        'provider' => 'yahoo_chart',
        'provider_symbol' => 'IBGS.MI',
        'decimals' => 2,
        'value_style' => 'money',
        'change_basis' => 'previous close',
    ],
    [
        'key' => 'gold',
        'name' => 'Gold (COMEX)',
        'symbol' => 'GC',
        'identifier' => 'Front-month futures',
        'provider' => 'yahoo_chart',
        'provider_symbol' => 'GC=F',
        'decimals' => 2,
        'value_style' => 'money',
        'change_basis' => 'previous close',
    ],
    [
        'key' => 'bitcoin',
        'name' => 'Bitcoin',
        'symbol' => 'BTC',
        'identifier' => 'BTC/USD',
        'provider' => 'coingecko',
        'provider_symbol' => 'bitcoin',
        'decimals' => 0,
        'value_style' => 'money',
        'change_basis' => '24 hours',
    ],
    [
        'key' => 'ethereum',
        'name' => 'Ethereum',
        'symbol' => 'ETH',
        'identifier' => 'ETH/USD',
        'provider' => 'coingecko',
        'provider_symbol' => 'ethereum',
        'decimals' => 2,
        'value_style' => 'money',
        'change_basis' => '24 hours',
    ],
    [
        'key' => 'cardano',
        'name' => 'Cardano',
        'symbol' => 'ADA',
        'identifier' => 'ADA/USD',
        'provider' => 'coingecko',
        'provider_symbol' => 'cardano',
        'decimals' => 4,
        'value_style' => 'money',
        'change_basis' => '24 hours',
    ],
];

