<?php

declare(strict_types=1);

return [
    'version' => 'deterministic-v4-freshness',
    'candidate_limit' => 250,
    'weights' => [
        'importance' => 0.32,
        'relevance' => 0.28,
        'evidence' => 0.18,
        'practical_impact' => 0.12,
        'novelty' => 0.10,
    ],
    'general' => [
        'importance_terms' => [
            'emergency' => 18, 'war' => 18, 'invasion' => 18, 'attack' => 14,
            'ceasefire' => 14, 'resigns' => 15, 'resignation' => 15, 'collapse' => 16,
            'bankruptcy' => 14, 'default' => 16, 'crisis' => 14, 'disaster' => 15,
            'earthquake' => 15, 'wildfire' => 13, 'flood' => 12, 'evacuation' => 13,
            'rate decision' => 15, 'interest rate' => 10, 'ban' => 11, 'sanctions' => 11,
            'regulation' => 9, 'court rules' => 12, 'approved' => 9, 'launches' => 6,
            'security breach' => 15, 'vulnerability' => 13, 'exploit' => 15, 'hack' => 13,
            'acquisition' => 9, 'merger' => 9, 'layoffs' => 8, 'shutdown' => 10,
        ],
        'practical_terms' => [
            'deadline' => 15, 'effective' => 10, 'takes effect' => 12, 'eligible' => 10,
            'tax' => 12, 'price' => 6, 'cost' => 8, 'mortgage' => 11, 'pension' => 11,
            'savings' => 9, 'jobs' => 9, 'employment' => 8, 'consumer' => 8,
            'business' => 7, 'investor' => 8, 'security update' => 13, 'patch' => 12,
            'available' => 7, 'open source' => 8, 'license' => 9, 'api' => 7,
        ],
        'low_value_terms' => [
            'opinion' => 6, 'what you need to know' => 4, 'live updates' => 3,
            'price prediction' => 18, 'could soar' => 18, 'expert predicts' => 16,
            'rumour' => 15, 'rumor' => 15, 'celebrity' => 18, 'sport' => 16,
            'watch:' => 4, 'podcast' => 4, 'weekly roundup' => 7,
        ],
    ],
    'sections' => [
        'breaking' => [
            'selection_threshold' => 40,
            'minimum_importance' => 32,
            'minimum_relevance' => 30,
            'cluster_hours' => 96,
            'relevance_terms' => [
                'government' => 7, 'president' => 7, 'prime minister' => 8, 'election' => 8,
                'military' => 10, 'missile' => 11, 'nuclear' => 13, 'terror' => 13,
                'central bank' => 10, 'financial stability' => 12, 'sovereign' => 10,
                'emergency' => 13, 'evacuation' => 10, 'death toll' => 11,
                'major outage' => 10, 'cyberattack' => 11, 'pandemic' => 12,
                'war' => 12, 'invasion' => 12, 'attack' => 10, 'sanctions' => 8,
                'crisis' => 9, 'disaster' => 12, 'flood' => 10, 'earthquake' => 12,
            ],
            'importance_terms' => [
                'declares war' => 24, 'state of emergency' => 22, 'military coup' => 24,
                'assassinated' => 24, 'government collapses' => 23, 'prime minister resigns' => 21,
                'president resigns' => 21, 'emergency rate' => 20, 'bank run' => 20,
                'sovereign default' => 23, 'mass casualty' => 22, 'critical infrastructure' => 17,
            ],
        ],
        'finance' => [
            'selection_threshold' => 34,
            'minimum_importance' => 20,
            'minimum_relevance' => 30,
            'cluster_hours' => 168,
            'relevance_terms' => [
                'central bank' => 14, 'ecb' => 14, 'federal reserve' => 14, 'bank of england' => 13,
                'interest rate' => 12, 'inflation' => 12, 'recession' => 12, 'gdp' => 10,
                'labour market' => 10, 'labor market' => 10, 'unemployment' => 10,
                'bank' => 8, 'credit' => 8, 'sovereign debt' => 12, 'bond' => 8,
                'budget' => 11, 'fiscal' => 11, 'tax' => 10, 'tariff' => 11,
                'trade' => 8, 'regulation' => 8, 'housing' => 9, 'mortgage' => 9,
                's&p 500' => 8, 'gold' => 7, 'etf' => 7,
                'fed' => 10, 'economic downturn' => 11, 'trade war' => 11,
            ],
            'importance_terms' => [
                'rate cut' => 15, 'rate hike' => 15, 'holds rates' => 10,
                'bank failure' => 20, 'bailout' => 18, 'debt crisis' => 18,
                'final budget' => 16, 'tariff package' => 15, 'capital controls' => 19,
                'market crash' => 20, 'record high' => 7, 'systemic risk' => 18,
                'economic downturn' => 16, 'trade war' => 14, 'price rises' => 8,
                'fed' => 7, 'financial crisis' => 18,
            ],
        ],
        'crypto' => [
            'selection_threshold' => 33,
            'minimum_importance' => 15,
            'minimum_relevance' => 35,
            'cluster_hours' => 168,
            'relevance_terms' => [
                'bitcoin' => 14, 'btc' => 9, 'ethereum' => 14, 'ether' => 9,
                'cardano' => 15, 'ada' => 8, 'stablecoin' => 11, 'custody' => 10,
                'exchange' => 8, 'wallet' => 7, 'protocol' => 9, 'blockchain' => 7,
                'mica' => 12, 'sec' => 9, 'regulation' => 10, 'institutional' => 8,
                'governance' => 10, 'treasury' => 9, 'upgrade' => 11, 'mainnet' => 10,
                'exploit' => 12, 'hack' => 12, 'security' => 10, 'outage' => 10,
            ],
            'importance_terms' => [
                'hard fork' => 16, 'security exploit' => 20, 'bridge hack' => 19,
                'exchange collapse' => 22, 'withdrawals halted' => 21, 'spot etf' => 14,
                'regulatory approval' => 15, 'court ruling' => 15, 'protocol upgrade' => 14,
                'treasury vote' => 13, 'network outage' => 17, 'depeg' => 17,
            ],
        ],
        'ai' => [
            'selection_threshold' => 33,
            'minimum_importance' => 15,
            'minimum_relevance' => 32,
            'cluster_hours' => 168,
            'relevance_terms' => [
                'artificial intelligence' => 12, ' ai ' => 9, 'model' => 8, 'llm' => 11,
                'agent' => 10, 'coding' => 8, 'computer use' => 11, 'multimodal' => 10,
                'open source' => 12, 'open-weight' => 12, 'local model' => 13,
                'qwen' => 14, 'deepseek' => 14, 'chinese model' => 13,
                'inference' => 9, 'quantization' => 10, 'benchmark' => 5, 'api' => 8,
                'semiconductor' => 9, 'chip' => 8, 'cybersecurity' => 9,
                'automation' => 10, 'deployment' => 10, 'productivity' => 9,
            ],
            'importance_terms' => [
                'major release' => 14, 'new model' => 10, 'open weights' => 14,
                'state of the art' => 7, 'agent platform' => 12, 'computer-use' => 13,
                'price cut' => 12, 'free tier' => 9, 'security incident' => 17,
                'data breach' => 18, 'export controls' => 16, 'regulatory framework' => 14,
                'production deployment' => 14, 'measured productivity' => 15,
            ],
        ],
        'italy' => [
            'selection_threshold' => 32,
            'minimum_importance' => 14,
            'minimum_relevance' => 30,
            'cluster_hours' => 168,
            'relevance_terms' => [
                'governo' => 10, 'consiglio dei ministri' => 14, 'decreto' => 11,
                'legge' => 10, 'approvato' => 9, 'entra in vigore' => 13,
                'fisco' => 12, 'tasse' => 12, 'scadenza' => 13, 'pensione' => 11,
                'sanità' => 11, 'salute' => 9, 'energia' => 9, 'lavoro' => 9,
                'imprese' => 8, 'famiglie' => 9, 'bonus' => 9, 'emergenza' => 13,
            ],
            'importance_terms' => [
                'decreto legge' => 15, 'stato di emergenza' => 20, 'riforma' => 12,
                'manovra' => 15, 'legge di bilancio' => 17, 'obbligo' => 13,
                'divieto' => 12, 'proroga' => 10, 'protezione civile' => 14,
            ],
        ],
        'local' => [
            'selection_threshold' => 28,
            'minimum_importance' => 10,
            'minimum_relevance' => 28,
            'cluster_hours' => 168,
            'relevance_terms' => [
                'bormio' => 15, 'livigno' => 15, 'sondalo' => 15,
                'valdidentro' => 15, 'valdisotto' => 15, 'valfurva' => 15,
                'alta valtellina' => 16, 'sondrio' => 10, 'lombardia' => 8,
                'viabilità' => 14, 'strada' => 10, 'trasporto' => 11,
                'chiusura' => 13, 'interruzione' => 13, 'allerta' => 15,
                'sanità' => 11, 'scuola' => 9, 'servizio' => 8,
            ],
            'importance_terms' => [
                'protezione civile' => 18, 'emergenza' => 18, 'allerta rossa' => 22,
                'chiusura strada' => 17, 'strada chiusa' => 17, 'frana' => 18,
                'valanga' => 18, 'alluvione' => 18, 'interruzione servizio' => 15,
                'ordinanza' => 12, 'scadenza' => 11, 'deviazione' => 12,
            ],
        ],
    ],
];
