<?php

declare(strict_types=1);

/**
 * Initial provider-neutral source catalogue.
 *
 * Stage 1 does not fetch these sources. Feed/API URLs will be verified before
 * enabling their adapters in Stage 3. A private local override can be placed
 * in config/sources.local.php; that file is ignored by Git.
 */
return [
    [
        'id' => 'bbc_world',
        'name' => 'BBC World',
        'url' => 'https://feeds.bbci.co.uk/news/world/rss.xml',
        'categories' => ['breaking'],
        'geography' => 'global',
        'source_type' => 'mainstream',
        'trust_level' => 4,
        'enabled' => true,
        'refresh_method' => 'rss',
        'notes' => 'Broad discovery and corroboration; prefer primary links when available.',
    ],
    [
        'id' => 'bbc_business',
        'name' => 'BBC Business',
        'url' => 'https://feeds.bbci.co.uk/news/business/rss.xml',
        'categories' => ['finance'],
        'geography' => 'global',
        'source_type' => 'mainstream',
        'trust_level' => 4,
        'enabled' => true,
        'refresh_method' => 'rss',
        'notes' => 'Candidate discovery; aggressive deterministic filtering required.',
    ],
    [
        'id' => 'bbc_technology',
        'name' => 'BBC Technology',
        'url' => 'https://feeds.bbci.co.uk/news/technology/rss.xml',
        'categories' => ['ai_business'],
        'geography' => 'global',
        'source_type' => 'mainstream',
        'trust_level' => 4,
        'enabled' => true,
        'refresh_method' => 'rss',
        'notes' => 'Exclude ordinary gadget and lifestyle coverage.',
    ],
    [
        'id' => 'ecb_press',
        'name' => 'European Central Bank',
        'url' => 'https://www.ecb.europa.eu/press/html/index.en.html',
        'categories' => ['breaking', 'finance'],
        'geography' => 'eu',
        'source_type' => 'primary',
        'trust_level' => 5,
        'enabled' => true,
        'refresh_method' => 'official_page',
        'notes' => 'Rate decisions, emergency actions, financial stability, and material policy changes.',
    ],
    [
        'id' => 'eu_commission_news',
        'name' => 'European Commission',
        'url' => 'https://commission.europa.eu/news-and-media_en',
        'categories' => ['finance', 'italy'],
        'geography' => 'eu',
        'source_type' => 'primary',
        'trust_level' => 5,
        'enabled' => true,
        'refresh_method' => 'official_page',
        'notes' => 'Budgets, fiscal rules, regulation, trade, and major shared programmes.',
    ],
    [
        'id' => 'italian_government',
        'name' => 'Presidenza del Consiglio dei Ministri',
        'url' => 'https://www.governo.it/',
        'categories' => ['breaking', 'finance', 'italy'],
        'geography' => 'italy',
        'source_type' => 'primary',
        'trust_level' => 5,
        'enabled' => true,
        'refresh_method' => 'official_page',
        'notes' => 'Approved decisions and measures, not routine political statements.',
    ],
    [
        'id' => 'regione_lombardia',
        'name' => 'Regione Lombardia',
        'url' => 'https://www.regione.lombardia.it/',
        'categories' => ['local'],
        'geography' => 'lombardy',
        'source_type' => 'primary',
        'trust_level' => 5,
        'enabled' => true,
        'refresh_method' => 'official_page',
        'notes' => 'Healthcare, transport, benefits, rules, public services, and emergencies.',
    ],
    [
        'id' => 'provincia_sondrio',
        'name' => 'Provincia di Sondrio',
        'url' => 'https://www.provinciasondrio.it/',
        'categories' => ['local'],
        'geography' => 'sondrio',
        'source_type' => 'primary',
        'trust_level' => 5,
        'enabled' => true,
        'refresh_method' => 'official_page',
        'notes' => 'Infrastructure, roads, services, environment, and major administrative decisions.',
    ],
    [
        'id' => 'comune_bormio',
        'name' => 'Comune di Bormio',
        'url' => 'https://www.comune.bormio.so.it/',
        'categories' => ['local'],
        'geography' => 'alta_valtellina',
        'source_type' => 'primary',
        'trust_level' => 5,
        'enabled' => true,
        'refresh_method' => 'official_page',
        'notes' => 'Actionable local notices; adapter robustness must be tested.',
    ],
    [
        'id' => 'hacker_news',
        'name' => 'Hacker News',
        'url' => 'https://hnrss.org/frontpage',
        'categories' => ['ai_business'],
        'geography' => 'global',
        'source_type' => 'signal',
        'trust_level' => 2,
        'enabled' => true,
        'refresh_method' => 'rss',
        'notes' => 'Discovery only. Verify important claims at their primary source.',
    ],
    [
        'id' => 'reddit_localllama',
        'name' => 'Reddit r/LocalLLaMA',
        'url' => 'https://www.reddit.com/r/LocalLLaMA/top.json?t=day&limit=25',
        'categories' => ['ai_business'],
        'geography' => 'global',
        'source_type' => 'signal',
        'trust_level' => 1,
        'enabled' => true,
        'refresh_method' => 'public_json',
        'notes' => 'Free public signal where available; respect rate limits and verify claims.',
    ],
    [
        'id' => 'x_curated',
        'name' => 'Curated X accounts',
        'url' => 'https://x.com/',
        'categories' => ['x_signals'],
        'geography' => 'global',
        'source_type' => 'signal',
        'trust_level' => 1,
        'enabled' => true,
        'refresh_method' => 'embed_or_public_page',
        'notes' => 'Five signals without a paid API. Availability may be limited; never treat as verified news.',
    ],
];

