<?php

declare(strict_types=1);

/**
 * Provider-neutral source catalogue.
 *
 * Stage 3 reads only entries marked stage3_active and using RSS/Atom. Sources
 * without a stable public feed remain documented here as later-stage adapters.
 * A private local override can be placed in config/sources.local.php.
 */
return [
    [
        'id' => 'yahoo_chart',
        'name' => 'Yahoo Finance chart endpoint',
        'url' => 'https://query1.finance.yahoo.com/v8/finance/chart/',
        'categories' => ['finance'],
        'geography' => 'global',
        'source_type' => 'market_data',
        'trust_level' => 3,
        'enabled' => true,
        'stage3_active' => false,
        'refresh_method' => 'public_json',
        'notes' => 'No-key market endpoint behind a replaceable adapter; unofficial and monitored carefully.',
    ],
    [
        'id' => 'coingecko',
        'name' => 'CoinGecko Keyless Public API',
        'url' => 'https://api.coingecko.com/api/v3/coins/markets',
        'categories' => ['finance'],
        'geography' => 'global',
        'source_type' => 'market_data',
        'trust_level' => 4,
        'enabled' => true,
        'stage3_active' => false,
        'refresh_method' => 'public_json',
        'notes' => 'One batched call for BTC, ETH, and ADA with IP-based rate limits.',
    ],

    // Breaking / critical intake: broad reporting plus a primary institutional feed.
    [
        'id' => 'bbc_world',
        'name' => 'BBC World',
        'url' => 'https://feeds.bbci.co.uk/news/world/rss.xml',
        'categories' => ['breaking'],
        'geography' => 'global',
        'source_type' => 'mainstream',
        'trust_level' => 4,
        'enabled' => true,
        'stage3_active' => true,
        'refresh_method' => 'rss',
        'notes' => 'Broad global baseline and corroboration; primary documents remain preferred when available.',
    ],
    [
        'id' => 'guardian_world',
        'name' => 'The Guardian World',
        'url' => 'https://www.theguardian.com/world/rss',
        'categories' => ['breaking'],
        'geography' => 'global',
        'source_type' => 'mainstream',
        'trust_level' => 4,
        'enabled' => true,
        'stage3_active' => true,
        'refresh_method' => 'rss',
        'notes' => 'Additional international reporting and useful coverage diversity.',
    ],
    [
        'id' => 'al_jazeera_all',
        'name' => 'Al Jazeera English',
        'url' => 'https://www.aljazeera.com/xml/rss/all.xml',
        'categories' => ['breaking'],
        'geography' => 'global',
        'source_type' => 'mainstream',
        'trust_level' => 4,
        'enabled' => true,
        'stage3_active' => true,
        'refresh_method' => 'rss',
        'notes' => 'Perspective-diverse international coverage, especially outside Europe and North America.',
    ],
    [
        'id' => 'un_news',
        'name' => 'United Nations News',
        'url' => 'https://news.un.org/feed/subscribe/en/news/all/rss.xml',
        'categories' => ['breaking'],
        'geography' => 'global',
        'source_type' => 'primary',
        'trust_level' => 5,
        'enabled' => true,
        'stage3_active' => true,
        'refresh_method' => 'rss',
        'notes' => 'Primary institutional reporting for humanitarian crises, diplomacy, and UN decisions.',
    ],

    // Finance: mainstream discovery, monetary-policy authority, expert and contrarian lenses.
    [
        'id' => 'bbc_business',
        'name' => 'BBC Business',
        'url' => 'https://feeds.bbci.co.uk/news/business/rss.xml',
        'categories' => ['finance'],
        'geography' => 'global',
        'source_type' => 'mainstream',
        'trust_level' => 4,
        'enabled' => true,
        'stage3_active' => true,
        'refresh_method' => 'rss',
        'notes' => 'Broad business discovery feed; Stage 4 will suppress ordinary company and market noise.',
    ],
    [
        'id' => 'ecb_press',
        'name' => 'European Central Bank news',
        'url' => 'https://www.ecb.europa.eu/rss/press.html',
        'categories' => ['breaking', 'finance'],
        'geography' => 'eu',
        'source_type' => 'primary',
        'trust_level' => 5,
        'enabled' => true,
        'stage3_active' => true,
        'refresh_method' => 'rss',
        'notes' => 'Primary monetary-policy decisions, press releases, speeches, and official explanations.',
    ],
    [
        'id' => 'calculated_risk',
        'name' => 'Calculated Risk · Bill McBride',
        'url' => 'https://www.calculatedriskblog.com/feeds/posts/default?alt=rss',
        'categories' => ['finance'],
        'geography' => 'us_global',
        'source_type' => 'field_expert',
        'trust_level' => 4,
        'enabled' => true,
        'stage3_active' => true,
        'refresh_method' => 'rss',
        'notes' => 'Evidence-led macro, housing, and banking analysis from a long-running independent analyst.',
    ],
    [
        'id' => 'wolf_street',
        'name' => 'Wolf Street · Wolf Richter',
        'url' => 'https://wolfstreet.com/feed/',
        'categories' => ['finance'],
        'geography' => 'us_global',
        'source_type' => 'contrarian',
        'trust_level' => 2,
        'enabled' => true,
        'stage3_active' => true,
        'refresh_method' => 'rss',
        'notes' => 'Skeptical counterweight on debt, housing, banks, and asset prices; analysis is not primary evidence.',
    ],

    // Crypto: protocol sources, specialist reporting, and skeptical counterweights.
    [
        'id' => 'bitcoin_core_news',
        'name' => 'Bitcoin Core',
        'url' => 'https://bitcoincore.org/en/feed.xml',
        'categories' => ['crypto'],
        'geography' => 'global',
        'source_type' => 'primary',
        'trust_level' => 5,
        'enabled' => true,
        'stage3_active' => true,
        'refresh_method' => 'rss',
        'notes' => 'Primary security and release announcements from the Bitcoin Core project.',
    ],
    [
        'id' => 'ethereum_foundation_blog',
        'name' => 'Ethereum Foundation Blog',
        'url' => 'https://blog.ethereum.org/feed.xml',
        'categories' => ['crypto'],
        'geography' => 'global',
        'source_type' => 'primary',
        'trust_level' => 5,
        'enabled' => true,
        'stage3_active' => true,
        'refresh_method' => 'rss',
        'notes' => 'Primary network upgrades, security, protocol research, and ecosystem changes.',
    ],
    [
        'id' => 'cardano_announcements',
        'name' => 'Cardano Forum Announcements',
        'url' => 'https://forum.cardano.org/c/announcements/13.rss',
        'categories' => ['crypto'],
        'geography' => 'global',
        'source_type' => 'primary_community',
        'trust_level' => 4,
        'enabled' => true,
        'stage3_active' => true,
        'refresh_method' => 'rss',
        'notes' => 'Cardano-focused release, governance, infrastructure, and ecosystem announcements.',
    ],
    [
        'id' => 'coindesk_crypto',
        'name' => 'CoinDesk',
        'url' => 'https://www.coindesk.com/arc/outboundfeeds/rss/',
        'categories' => ['crypto'],
        'geography' => 'global',
        'source_type' => 'specialist',
        'trust_level' => 3,
        'enabled' => true,
        'stage3_active' => true,
        'refresh_method' => 'rss',
        'notes' => 'Broad specialist discovery; consequential claims should be checked against primary sources.',
    ],
    [
        'id' => 'protos_crypto',
        'name' => 'Protos',
        'url' => 'https://protos.com/feed/',
        'categories' => ['crypto'],
        'geography' => 'global',
        'source_type' => 'investigative',
        'trust_level' => 3,
        'enabled' => true,
        'stage3_active' => true,
        'refresh_method' => 'rss',
        'notes' => 'Investigative reporting on market structure, enforcement, fraud, and industry claims.',
    ],
    [
        'id' => 'web3_is_going_great',
        'name' => 'Web3 Is Going Just Great · Molly White',
        'url' => 'https://www.web3isgoinggreat.com/feed.xml',
        'categories' => ['crypto'],
        'geography' => 'global',
        'source_type' => 'contrarian',
        'trust_level' => 3,
        'enabled' => true,
        'stage3_active' => true,
        'refresh_method' => 'rss',
        'notes' => 'Documented skeptical counterweight covering hacks, failures, governance, and consumer harm.',
    ],

    // AI / technology / business: official releases plus expert and community signals.
    [
        'id' => 'bbc_technology',
        'name' => 'BBC Technology',
        'url' => 'https://feeds.bbci.co.uk/news/technology/rss.xml',
        'categories' => ['ai_business'],
        'geography' => 'global',
        'source_type' => 'mainstream',
        'trust_level' => 4,
        'enabled' => true,
        'stage3_active' => true,
        'refresh_method' => 'rss',
        'notes' => 'Broad technology context; Stage 4 will remove gadgets, lifestyle pieces, and minor product updates.',
    ],
    [
        'id' => 'openai_news',
        'name' => 'OpenAI News',
        'url' => 'https://openai.com/news/rss.xml',
        'categories' => ['ai_business'],
        'geography' => 'global',
        'source_type' => 'primary',
        'trust_level' => 5,
        'enabled' => true,
        'stage3_active' => true,
        'refresh_method' => 'rss',
        'notes' => 'Primary OpenAI product, research, safety, security, and company announcements.',
    ],
    [
        'id' => 'google_ai_blog',
        'name' => 'Google AI Blog',
        'url' => 'https://blog.google/technology/ai/rss/',
        'categories' => ['ai_business'],
        'geography' => 'global',
        'source_type' => 'primary',
        'trust_level' => 5,
        'enabled' => true,
        'stage3_active' => true,
        'refresh_method' => 'rss',
        'notes' => 'Primary Google and DeepMind AI product, research, and policy announcements.',
    ],
    [
        'id' => 'qwen_blog',
        'name' => 'Qwen Team Blog',
        'url' => 'https://qwenlm.github.io/blog/index.xml',
        'categories' => ['ai_business'],
        'geography' => 'china_global',
        'source_type' => 'primary',
        'trust_level' => 5,
        'enabled' => true,
        'stage3_active' => true,
        'refresh_method' => 'rss',
        'notes' => 'Primary Chinese open-model releases, technical reports, tooling, and efficiency updates.',
    ],
    [
        'id' => 'hugging_face_blog',
        'name' => 'Hugging Face Blog',
        'url' => 'https://huggingface.co/blog/feed.xml',
        'categories' => ['ai_business'],
        'geography' => 'global',
        'source_type' => 'ecosystem',
        'trust_level' => 3,
        'enabled' => true,
        'stage3_active' => true,
        'refresh_method' => 'rss',
        'notes' => 'Open-source ecosystem discovery; community posts require author and primary-source checks.',
    ],
    [
        'id' => 'simon_willison',
        'name' => 'Simon Willison’s Weblog',
        'url' => 'https://simonwillison.net/atom/everything-but-beats/',
        'categories' => ['ai_business'],
        'geography' => 'global',
        'source_type' => 'field_expert',
        'trust_level' => 4,
        'enabled' => true,
        'stage3_active' => true,
        'refresh_method' => 'atom',
        'notes' => 'Hands-on independent testing of models, agents, local tools, and real implementation limits.',
    ],
    [
        'id' => 'import_ai',
        'name' => 'Import AI · Jack Clark',
        'url' => 'https://importai.substack.com/feed',
        'categories' => ['ai_business'],
        'geography' => 'global',
        'source_type' => 'field_expert',
        'trust_level' => 3,
        'enabled' => true,
        'stage3_active' => true,
        'refresh_method' => 'rss',
        'notes' => 'Expert synthesis of AI research, policy, capability, and strategic implications.',
    ],
    [
        'id' => 'interconnects_ai',
        'name' => 'Interconnects · Nathan Lambert',
        'url' => 'https://www.interconnects.ai/feed',
        'categories' => ['ai_business'],
        'geography' => 'global',
        'source_type' => 'field_expert',
        'trust_level' => 3,
        'enabled' => true,
        'stage3_active' => true,
        'refresh_method' => 'rss',
        'notes' => 'Independent technical analysis of open models, training, post-training, and industry strategy.',
    ],
    [
        'id' => 'hacker_news',
        'name' => 'Hacker News Front Page',
        'url' => 'https://hnrss.org/frontpage',
        'categories' => ['ai_business'],
        'geography' => 'global',
        'source_type' => 'signal',
        'trust_level' => 2,
        'enabled' => true,
        'stage3_active' => true,
        'refresh_method' => 'rss',
        'notes' => 'Discovery only; the linked original source must support any important claim.',
    ],
    [
        'id' => 'reddit_localllama',
        'name' => 'Reddit r/LocalLLaMA',
        'url' => 'https://www.reddit.com/r/LocalLLaMA/top/.rss?t=week',
        'categories' => ['ai_business'],
        'geography' => 'global',
        'source_type' => 'signal',
        'trust_level' => 1,
        'enabled' => true,
        'stage3_active' => true,
        'refresh_method' => 'atom',
        'notes' => 'Free community signal for local and open models; never evidence without verification.',
    ],

    // Planned source-specific adapters for later stages.
    [
        'id' => 'esma_crypto',
        'name' => 'ESMA crypto-assets updates',
        'url' => 'https://www.esma.europa.eu/esmas-activities/digital-finance-and-innovation/markets-crypto-assets-regulation-mica',
        'categories' => ['crypto', 'finance'],
        'geography' => 'eu',
        'source_type' => 'primary',
        'trust_level' => 5,
        'enabled' => true,
        'stage3_active' => false,
        'refresh_method' => 'official_page',
        'notes' => 'Planned page adapter for material MiCA, custody, stablecoin, and market-structure changes.',
    ],
    [
        'id' => 'eu_commission_news',
        'name' => 'European Commission',
        'url' => 'https://commission.europa.eu/news-and-media_en',
        'categories' => ['finance', 'italy'],
        'geography' => 'eu',
        'source_type' => 'primary',
        'trust_level' => 5,
        'enabled' => true,
        'stage3_active' => false,
        'refresh_method' => 'official_page',
        'notes' => 'Planned page adapter for budgets, fiscal rules, regulation, trade, and shared programmes.',
    ],
    [
        'id' => 'italian_government',
        'name' => 'Presidenza del Consiglio dei Ministri',
        'url' => 'https://www.governo.it/feed/rss',
        'categories' => ['breaking', 'finance', 'italy'],
        'geography' => 'italy',
        'source_type' => 'primary',
        'trust_level' => 5,
        'enabled' => true,
        'stage3_active' => true,
        'refresh_method' => 'rss',
        'notes' => 'Official RSS for approved government decisions and measures; routine statements remain subject to ranking.',
    ],
    [
        'id' => 'regione_lombardia',
        'name' => 'Regione Lombardia',
        'url' => 'https://www.regione.lombardia.it/',
        'categories' => ['local'],
        'geography' => 'lombardy',
        'source_type' => 'primary',
        'trust_level' => 5,
        'enabled' => true,
        'stage3_active' => false,
        'refresh_method' => 'official_page',
        'notes' => 'Planned local adapter for healthcare, transport, benefits, public services, and emergencies.',
    ],
    [
        'id' => 'provincia_sondrio',
        'name' => 'Provincia di Sondrio',
        'url' => 'https://www.provinciasondrio.it/',
        'categories' => ['local'],
        'geography' => 'sondrio',
        'source_type' => 'primary',
        'trust_level' => 5,
        'enabled' => true,
        'stage3_active' => false,
        'refresh_method' => 'official_page',
        'notes' => 'Planned local adapter for roads, infrastructure, services, and environment.',
    ],
    [
        'id' => 'comune_bormio',
        'name' => 'Comune di Bormio',
        'url' => 'https://www.comune.bormio.so.it/it/news/feed',
        'categories' => ['local'],
        'geography' => 'alta_valtellina',
        'source_type' => 'primary',
        'trust_level' => 5,
        'enabled' => true,
        'stage3_active' => true,
        'refresh_method' => 'rss',
        'notes' => 'Official municipal news feed for actionable Bormio notices.',
    ],
    [
        'id' => 'comune_livigno',
        'name' => 'Comune di Livigno',
        'url' => 'https://www.comune.livigno.so.it/it/news/feed',
        'categories' => ['local'],
        'geography' => 'alta_valtellina',
        'source_type' => 'primary',
        'trust_level' => 5,
        'enabled' => true,
        'stage3_active' => true,
        'refresh_method' => 'rss',
        'notes' => 'Official municipal news feed for actionable Livigno notices.',
    ],
    [
        'id' => 'comune_sondalo',
        'name' => 'Comune di Sondalo',
        'url' => 'https://www.comune.sondalo.so.it/it/news/feed',
        'categories' => ['local'],
        'geography' => 'alta_valtellina',
        'source_type' => 'primary',
        'trust_level' => 5,
        'enabled' => true,
        'stage3_active' => true,
        'refresh_method' => 'rss',
        'notes' => 'Official municipal news feed for actionable Sondalo notices.',
    ],
    [
        'id' => 'comune_valdidentro',
        'name' => 'Comune di Valdidentro',
        'url' => 'https://www.comune.valdidentro.so.it/it/news/feed',
        'categories' => ['local'],
        'geography' => 'alta_valtellina',
        'source_type' => 'primary',
        'trust_level' => 5,
        'enabled' => true,
        'stage3_active' => true,
        'refresh_method' => 'rss',
        'notes' => 'Official municipal news feed for actionable Valdidentro notices.',
    ],
    [
        'id' => 'comune_valdisotto',
        'name' => 'Comune di Valdisotto',
        'url' => 'https://www.comune.valdisotto.so.it/it/news/feed',
        'categories' => ['local'],
        'geography' => 'alta_valtellina',
        'source_type' => 'primary',
        'trust_level' => 5,
        'enabled' => true,
        'stage3_active' => true,
        'refresh_method' => 'rss',
        'notes' => 'Official municipal news feed for actionable Valdisotto notices.',
    ],
    [
        'id' => 'comune_valfurva',
        'name' => 'Comune di Valfurva',
        'url' => 'https://www.comune.valfurva.so.it/it/news/feed',
        'categories' => ['local'],
        'geography' => 'alta_valtellina',
        'source_type' => 'primary',
        'trust_level' => 5,
        'enabled' => true,
        'stage3_active' => true,
        'refresh_method' => 'rss',
        'notes' => 'Official municipal news feed for actionable Valfurva notices.',
    ],
    [
        'id' => 'x_curated',
        'name' => 'Curated X accounts',
        'url' => 'https://x.com/',
        'categories' => ['x_signals'],
        'geography' => 'global',
        'source_type' => 'signal',
        'trust_level' => 1,
        'enabled' => true,
        'stage3_active' => false,
        'refresh_method' => 'embed_or_public_page',
        'notes' => 'Planned five-signal embed without a paid API; never treated as verified news.',
    ],
];
